#ifndef __NUTTX_DRIVERS_WIRELESS_VIRTUAL_MAC80211_HWSIM_H
#define __NUTTX_DRIVERS_WIRELESS_VIRTUAL_MAC80211_HWSIM_H

#include "mac80211_hwsim_linux.h"

#endif /* __NUTTX_DRIVERS_WIRELESS_VIRTUAL_MAC80211_HWSIM_H */
