#ifndef __WIRELESS_IEEE80211_INCLUDE_NET_PKT_SCHED_H
#define __WIRELESS_IEEE80211_INCLUDE_NET_PKT_SCHED_H

#define TC_PRIO_BESTEFFORT 0
#define TC_PRIO_FILLER 1
#define TC_PRIO_BULK 2
#define TC_PRIO_INTERACTIVE_BULK 4
#define TC_PRIO_INTERACTIVE 6
#define TC_PRIO_CONTROL 7
#define TC_PRIO_MAX 15

#endif
