#ifndef __WIRELESS_IEEE80211_INCLUDE_NET_NETNS_GENERIC_H
#define __WIRELESS_IEEE80211_INCLUDE_NET_NETNS_GENERIC_H

#include <net/net_namespace.h>

#endif /* __WIRELESS_IEEE80211_INCLUDE_NET_NETNS_GENERIC_H */
