#ifndef __WIRELESS_IEEE80211_INCLUDE_LINUX_VIRTIO_IDS_H
#define __WIRELESS_IEEE80211_INCLUDE_LINUX_VIRTIO_IDS_H

#define VIRTIO_ID_MAC80211_HWSIM 29
#define VIRTIO_DEV_ANY_ID       0xffffffff

#endif
