#ifndef __WIRELESS_LINUX_BLUETOOTH_COMPAT_LINUX_SCHED_H
#define __WIRELESS_LINUX_BLUETOOTH_COMPAT_LINUX_SCHED_H
#define TASK_INTERRUPTIBLE 1
#define TASK_RUNNING 0
#define MAX_SCHEDULE_TIMEOUT (~0UL)
#endif
