#ifndef __WIRELESS_LINUX_BLUETOOTH_COMPAT_LINUX_SOCKIOS_H
#define __WIRELESS_LINUX_BLUETOOTH_COMPAT_LINUX_SOCKIOS_H

#define SIOCINQ  0x541b
#define SIOCOUTQ 0x5411
#define SIOCETHTOOL 0x8946

#endif
